Repository brazil-data-cube/metadata, pull requests merged in 2024-03, with the labels that each got.

#8 Add MYD13Q1 collections
  myd13q1-v60.json
  myd13q1-v61.json
Labels: enhancement

#11 update titles
  landsat-16d.json
  s2-16d.json
Labels: documentation

#12 Remove non-existent B10
  s2-l2a-bundle.json
Labels: bug

#9 Add CBERS MUX Cube metadata
  cbers4-mux-2m.json
Labels: enhancement

#10 Add GOES-16/ABI Collection
  goes16-l2-cmi.json
Labels: enhancement

#16 It's CBERS-4 Data Cubes 🎉
  cbers-wfi-8d.json
  cbers4-wfi-16d.json
Labels: enhancement

#17 Modis bundles
  mod13q1-v61-bundle.json
  myd13q1-v61-bundle.json
Labels: enhancement

#14 MetaData Review: Insert Assets Title, thumbnail on modis and Standardize indentation
  amz1_wfi_l4_sr.json
  cb4_mux_l4_sr.json
  cb4_wfi_l4_sr.json
  cb4a_wfi_l4_sr.json
  cb4a_wpm_pca_fused.json
  cbers4-mux-2m.json
  landsat-16d.json
  landsat.json
  mod13q1-v60.json
  mod13q1-v61.json
  myd13q1-v60.json
  myd13q1-v61.json
  s1-grd-bundle.json
  s2-16d.json
  s2-l1c-bundle.json
  s2-l2a-bundle.json
  s2-l2a.json
  s3-olci-bundle.json
Labels: documentation

#15 Add Mosaics
  mosaics/composed/landsat-3m-amazonia.json
  mosaics/identity/landsat-3m-amazonia-idt.json
  mosaics/products/mosaic-cb4-brazil-3m.json
  mosaics/products/mosaic-cb4a-paraiba-3m.json
  mosaics/products/mosaic-landsat-amazon-3m.json
  mosaics/products/mosaic-landsat-brazil-6m.json
  mosaics/products/mosaic-s2-amazonia-3m.json
  mosaics/products/mosaic-s2-cerrado-2m.json
  mosaics/products/mosaic-s2-cerrado-4m.json
  mosaics/products/mosaic-s2-paraiba-3m.json
  mosaics/products/mosaic-s2-yanomami_territory-6m.json
Labels: enhancement
