Repository brazil-data-cube/metadata, pull requests merged in 2025-02, with the labels that each got.

#83 Update CBERS DN id and descriptions
  cbers/cb4/cb4-mux-l2-dn.json
  cbers/cb4/cb4-mux-l4-dn.json
  cbers/cb4/cb4-pan10m-l2-dn.json
  cbers/cb4/cb4-pan10m-l4-dn.json
  cbers/cb4/cb4-pan5m-l2-dn.json
  cbers/cb4/cb4-pan5m-l4-dn.json
  cbers/cb4/cb4-wfi-l2-dn.json
  cbers/cb4/cb4-wfi-l4-dn.json
Labels: documentation

#85 Fix Title Typo
  cbers/cb4/cb4-mux-l4-dn.json
Labels: documentation

#86 Update cbers metadata
  cbers/cb4/cb4-mux-l4-dn.json
  cbers/cb4/cb4-mux-l4-sr.json
  cbers/cb4/cb4-wfi-l2-dn.json
  cbers/cb4/cb4-wfi-l4-dn.json
Labels: documentation

#87 Standardize CBERS metadata
  cbers/cb4a/cb4a-wfi-l4-sr.json
  cbers/todo/cb2b-ccd-l2-dn.json
  cbers/todo/cb2b-hrc-l2-dn.json
  cbers/todo/cb2b-wfi-l2-dn.json
  cbers/todo/cb4a-mux-l2-dn.json
  cbers/todo/cb4a-mux-l4-dn.json
  cbers/todo/cb4a-wfi-l2-dn.json
  cbers/todo/cb4a-wfi-l4-dn.json
  cbers/todo/cb4a-wpm-l2-dn.json
  cbers/todo/cb4a-wpm-l4-dn.json
Labels: documentation

#21 new file: prec_merge_daily.json
  prec_merge_daily.json
  prec_merge_hourly.json
Labels: enhancement

#102 Adjust precipitation metadata
  climatic/prec_merge_daily.json
  climatic/prec_merge_hourly.json
Labels: enhancement

#107 Start temperature metadata
  climatic/samet_daily.json
  climatic/samet_hourly.json
Labels: enhancement

#109 Update SAMeT metadata
  climatic/samet_daily.json
  climatic/samet_hourly.json
Labels: enhancement

#111 :bug: fix typo in CBERS2 Band Name
  cbers/todo/cb2-ccd-l2-dn.json
  cbers/todo/cb2b-ccd-l2-dn.json
Labels: bug

#113 :sparkle: It's Pleiades!
  pleiades/pleiades-ortho_enhanced.json
Labels: enhancement

#110 Create mosaic-amazonia1-brazil-3m.json
  mosaics/products/mosaic-amazonia1-brazil-3m.json
Labels: enhancement

#114 :sparkle: It's Pleiades!
  pleiades/pleiades-ortho_enhanced.json
Labels: enhancement
